### ISSUE TITLE
PGIS tools: calculates daily and monthly averages 

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/cardatdbtools#3]
with a threshold variable to determine the min % of values needed for an average.

**Comment by ivanhanigan** [comment]
@ChristyGeromboux there seems to be a bug?
```r
sql <- cardat_daily_averages(var = "pm25", state = "all", threshold = 0.7, 
                             year = "all")
cat(sql)
sql <- "
select l.state, l.station, l.lat, l.lon, d.date, d.variable, avg(d.value), d.units, d.measurement_method, count(*) as number_of_readings
from air_pollution_monitors.ap_monitor_locations_master as l, 
    air_pollution_monitors.ap_monitor_data_master d
where d.station = l.station
    and d.state = l.state
    and d.variable in (pm25)
    all
group by l.state l.station, l.lat, l.lon, d.date, d.variable, d.units, d.measurement_method, 
    having count(*)>=16.8
"
```
I think the year = 'all' should return an empty string for the where clause, but as you can see it says "all"
Also there is a missing comma , in group_by between state and l.station, and the pm needs quote andthere is a superfluos comma , at  end group by before having

**Comment by ChristyGeromboux** [comment]
Sorry - forgot to commit after fixing these issues - should be correct now.
