### ISSUE TITLE
AP Database: UTC time field incorrect

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/cardatdbtools#9]
NAPMD using the datetime_utc field - that field is not correct for most (all?) of the timstamps and we never got around to fixing

**Comment by ivanhanigan** [comment]
@cassandrayuen Today we chatted about conversion on NAPMD of data holdings to show correct UTC

**Comment by cassandrayuen** [comment]
Fixed on ap_monitor_data_master and also unpublished tables for QLD (2006-2009), based on local time using non-daylight savings time zone.
